### PR TITLE
Getting started on the UI

### PR DESCRIPTION
**Pull request by evanmuller**
@priyadarshy, @bone-saw, @brunobernardino 

This will be the RN frontend. Right now it just displays a list of tasks that it fetches via a graphql query. It subscribes to changes and updates the list appropriately.

### CODE REVIEW

**Comment by BrunoBernardino** [comment]
Thanks!

**Comment by bone-saw** [comment]
Looks like you've made good progress. When you've got things kind of working, feel free to share screenshots or a short demo vid so we can chime in with feedback without needing to pull down <3

**Comment by evanmuller** [comment]
I just added the calendar mini map and the ability to change the current day. There's a little more to it visually now :).

Here are some [screeshots](https://photos.app.goo.gl/nWkpvsRezAKv4Su78)

**Comment by evanmuller** [comment]
Here are some [screenshots](https://photos.app.goo.gl/AB4AcdyppHFWTG1b9) of the move behavior.

**Comment by bone-saw** [comment]
Thanks for the screenshots! It looks like you've got most of the core UI in place. Nothing major seems off / missing to me.

Only one observation - I noticed you had a task in there for "Add the ability to move tasks". If you'd rather not spend the time on this, don't sweat it. When we built drag and drop in our mobile app beta, it was more time consuming than we thought, so don't want you to get bogged down as well. On the other hand, if it seems easy to you, by all means :)

**Comment by evanmuller** [comment]
@bone-saw You're welcome for the screens and I'm glad nothing major seems off :). The fonts and icons don't match exactly. It looks like the Avenir font you're using is a paid for font so I tried to match it as best as I could with a the free versions, but it isn't exact. The same with the font awesome fronts, looks like you're using pro and I'm using the free version so it's no exactly the same. I also don't like the little dot under the selected day in the calendar, it wasn't immediately obvious to me how to get rid of it, but I did attempt to :).

I also made the "complete task" button slightly larger than what you have in the storyboard. I've read that 42x42 should really be the smallest you go for mobile device buttons. I made it 32x32 so it's a little larger, proportionally, than what you have in the storyboard, to make it a little easier to hit. Maybe the intent was for that "complete task" icon to not be a button at all, the storyboard doesn't specify that it needs to be. Maybe that'd be a better way to go, but for the purposes of this exercise/testing, its convenient for it to be a button.

I wasn't actually planning on doing DND, but thanks for the heads up. All I meant by: "Add the ability to move tasks", was to add the ability to change a task's start date.

I'm going to merge in this PR. I believe this meets the base feature set, but I'm still going to hack on this a bit. I'll create a new PR for anything I add.

**Comment by bone-saw** [comment]
We are indeed on that paid Avenir and Font Awesome train. Appreciate you being thoughtful in looking for alternatives.

Also, you're right that the storyboard checkmark buttons are so small that they create a frustrating touch experience. Just making the checkmark bigger, as you've done, is a reasonable step to fix this. This is currently an issue in several places in the production version of the mobile app beta. What I'm hoping to do is create enough padding around the icons, while keeping them similar to their current size/proportion, so that they don't look enormous but still feel good to touch.

Looking forward to seeing everything in action tomorrow!

**Pull request merged**
